/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arrownock_internal_push_NativeAPIs */

#ifndef _Included_com_arrownock_internal_push_NativeAPIs
#define _Included_com_arrownock_internal_push_NativeAPIs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arrownock_internal_push_NativeAPIs
 * Method:    runDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_arrownock_internal_push_NativeAPIs_runDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_arrownock_internal_push_NativeAPIs
 * Method:    startDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_arrownock_internal_push_NativeAPIs_startDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
